#!/usr/bin/env bash
# scripts/refresh-context.sh — regenerate volatile counts into metrics.md
# Does NOT overwrite implementation-status.md (hand-maintained REAL/MOCK tables).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

out=".agents/context/metrics.md"
mkdir -p .agents/context

{
  echo "# Context metrics"
  echo
  echo "> Auto-generated by \`scripts/refresh-context.sh\`. Do not hand-edit."
  echo "> Route REAL/MOCK tables live in \`implementation-status.md\` — update those in the same PR."
  echo
  echo "**Generated:** $(date +%F)"
  echo
  echo "| Metric | Value |"
  echo "|--------|-------|"
  for app in client admin landing umpire; do
    p=$(find "apps/$app/src/app" -name 'page.tsx' 2>/dev/null | wc -l | tr -d ' ')
    r=$(find "apps/$app/src/app" -name 'route.ts' 2>/dev/null | wc -l | tr -d ' ')
    echo "| $app pages / route handlers | $p / $r |"
  done
  models=$(grep -rhc '^model ' packages/db/prisma/*.prisma 2>/dev/null | paste -sd+ - | bc 2>/dev/null || echo "?")
  echo "| Prisma models | $models |"
  migrations=$(find packages/db/prisma/migrations -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l | tr -d ' ')
  echo "| Migrations | $migrations |"
  specs=$(find openspec/specs -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l | tr -d ' ')
  echo "| OpenSpec domains | $specs |"
  use_server=$(grep -rl "['\"]use server['\"]" apps packages --include='*.ts' --include='*.tsx' 2>/dev/null | wc -l | tr -d ' ')
  echo "| \\\`'use server'\\\` files | $use_server |"
  mock_files=$(grep -rl 'MOCK_' apps --include='*.ts' --include='*.tsx' 2>/dev/null | wc -l | tr -d ' ')
  echo "| Files containing MOCK_ | $mock_files |"
  tests=$(find apps packages \( -name '*.test.*' -o -name '*.spec.*' \) 2>/dev/null | grep -v node_modules | wc -l | tr -d ' ' || true)
  echo "| Test files | ${tests:-0} |"
  commits=$(git log --since='30 days ago' --oneline 2>/dev/null | wc -l | tr -d ' ' || true)
  echo "| Commits (30d) | ${commits:-0} |"
} > "$out"

echo "Wrote $out"
