import type { SessionDiscoveryItem } from "@/types/session-discovery";

/** Shared venue — Sunrise Badminton Center, Cebu City (two sessions, different times). */
const SUNRISE_VENUE = {
	lat: 10.316,
	lng: 123.885,
	location: "Sunrise Badminton Center",
	venueAddress: "Juan Luna Ave, Cebu City, Cebu",
	venueKey: "10.316_123.885",
	clubId: "club-sunrise-cebu",
	clubName: "Sunrise Badminton Club",
} as const;

function daysFromNow(days: number, hour: number, minute = 0): string {
	const d = new Date();
	d.setDate(d.getDate() + days);
	d.setHours(hour, minute, 0, 0);
	return d.toISOString();
}

function hoursFromNow(hours: number): string {
	return new Date(Date.now() + hours * 60 * 60 * 1000).toISOString();
}

export const MOCK_SESSION_DISCOVERY: SessionDiscoveryItem[] = [
	{
		id: "sess-sunrise-today",
		isOwner: false,
		clubId: SUNRISE_VENUE.clubId,
		clubName: SUNRISE_VENUE.clubName,
		location: SUNRISE_VENUE.location,
		venueAddress: SUNRISE_VENUE.venueAddress,
		coordinates: { lat: SUNRISE_VENUE.lat, lng: SUNRISE_VENUE.lng },
		venueKey: SUNRISE_VENUE.venueKey,
		dateTime: hoursFromNow(2),
		endTime: hoursFromNow(5),
		status: "open",
		scheduleType: "mmr",
		origin: "club_queue",
		totalSlots: 16,
		acceptedCount: 10,
		playersPerCourt: 4,
		distanceKm: null,
		recentPlayers: [
			{ id: "p1", displayName: "Miguel R.", avatarUrl: null },
			{ id: "p2", displayName: "Ana L.", avatarUrl: null },
			{ id: "p3", displayName: "Carlos D.", avatarUrl: null },
		],
	},
	{
		id: "sess-sunrise-weekend",
		isOwner: false,
		clubId: SUNRISE_VENUE.clubId,
		clubName: SUNRISE_VENUE.clubName,
		location: SUNRISE_VENUE.location,
		venueAddress: SUNRISE_VENUE.venueAddress,
		coordinates: { lat: SUNRISE_VENUE.lat, lng: SUNRISE_VENUE.lng },
		venueKey: SUNRISE_VENUE.venueKey,
		dateTime: daysFromNow(2, 9, 0),
		endTime: daysFromNow(2, 12, 0),
		status: "open",
		scheduleType: "fun_games",
		origin: "club_queue",
		totalSlots: 12,
		acceptedCount: 12,
		playersPerCourt: 4,
		distanceKm: null,
		recentPlayers: [
			{ id: "p4", displayName: "Jenny T.", avatarUrl: null },
			{ id: "p5", displayName: "Mark S.", avatarUrl: null },
		],
	},
	{
		id: "sess-mandaue-live",
		isOwner: false,
		clubId: "club-mandaue-sports",
		clubName: "Mandaue Sports Hub",
		location: "Mandaue City Sports Complex",
		venueAddress: "Cebu North Rd, Mandaue City, Cebu",
		coordinates: { lat: 10.324, lng: 123.923 },
		venueKey: "10.324_123.923",
		dateTime: hoursFromNow(-1),
		endTime: hoursFromNow(2),
		status: "active",
		scheduleType: "mmr",
		origin: "club_queue",
		totalSlots: 8,
		acceptedCount: 8,
		playersPerCourt: 4,
		distanceKm: null,
		recentPlayers: [
			{ id: "p6", displayName: "Rico B.", avatarUrl: null },
			{ id: "p7", displayName: "Liza M.", avatarUrl: null },
			{ id: "p8", displayName: "Paolo G.", avatarUrl: null },
		],
	},
	{
		id: "sess-lapulapu-open",
		isOwner: false,
		clubId: "club-lapulapu",
		clubName: "Lapu-Lapu Smashers",
		location: "Hoops Dome Lapu-Lapu",
		venueAddress: "Gun-ob, Lapu-Lapu City, Cebu",
		coordinates: { lat: 10.31, lng: 123.949 },
		venueKey: "10.310_123.949",
		dateTime: daysFromNow(1, 18, 30),
		endTime: daysFromNow(1, 21, 30),
		status: "open",
		scheduleType: "fun_games",
		origin: "player_organized",
		totalSlots: 8,
		acceptedCount: 3,
		playersPerCourt: 4,
		distanceKm: null,
		recentPlayers: [{ id: "p9", displayName: "Diane K.", avatarUrl: null }],
	},
	{
		id: "sess-cebu-downtown",
		isOwner: false,
		clubId: "club-cebu-central",
		clubName: "Cebu Central Que",
		location: "Cebu IT Park Courts",
		venueAddress: "Jose Maria del Mar St, Cebu City, Cebu",
		coordinates: { lat: 10.329, lng: 123.905 },
		venueKey: "10.329_123.905",
		dateTime: daysFromNow(0, 19, 0),
		endTime: daysFromNow(0, 22, 0),
		status: "open",
		scheduleType: "mmr",
		origin: "club_queue",
		totalSlots: 20,
		acceptedCount: 14,
		playersPerCourt: 4,
		distanceKm: null,
		recentPlayers: [
			{ id: "p10", displayName: "Kevin W.", avatarUrl: null },
			{ id: "p11", displayName: "Sofia H.", avatarUrl: null },
		],
	},
	{
		id: "sess-talisay-weekend",
		isOwner: false,
		clubId: "club-talisay",
		clubName: "Talisay Shuttle Club",
		location: "Talisay Sports Center",
		venueAddress: "Tabunok, Talisay City, Cebu",
		coordinates: { lat: 10.244, lng: 123.848 },
		venueKey: "10.244_123.848",
		dateTime: daysFromNow(5, 8, 0),
		endTime: daysFromNow(5, 11, 0),
		status: "open",
		scheduleType: null,
		origin: "player_organized",
		totalSlots: 8,
		acceptedCount: 2,
		playersPerCourt: 4,
		distanceKm: null,
		recentPlayers: [],
	},
];
